(function(g){var window=this;'use strict';var Lrb=function(a,b){a.kb("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.jv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.dh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.US&&(b.lengthText?(e=b.lengthText||null,f=b.hw||null):b.lengthSeconds&&(e=g.jH(b.lengthSeconds),f=g.jH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.zRa(d).type;var l=b instanceof g.US?b.isLivePlayback:null,m=b instanceof g.US?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.qK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Ok(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Wr};b instanceof g.TS&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.U(),c=b.D;
g.V.call(this,{I:"a",S:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",La:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},V:[{I:"div",Y:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],ya:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",
La:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",ya:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",La:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ya:"{{title}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ya:"{{author}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ya:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.V({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({I:"div",S:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ya:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.X:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},V:[{I:"div",Y:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],
ya:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",La:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",ya:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",ya:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",ya:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",ya:"{{author_and_views}}"}]}]}]});
g.N(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ha("ytp-autonav-endscreen-link-container"),"click",this.PS);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({I:"div",S:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.V({I:"div",S:"ytp-autonav-endscreen-button-container"});g.N(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.V({I:"button",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancel autoplay"},ya:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.Ta("click",this.V1,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.V({I:"a",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},ya:"Play Now"});g.N(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.Ta("click",this.PS,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Mrb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Su(function(){Nrb(c)},
500);
g.N(this,this.D);this.OS();this.T(a,"autonavvisibility",this.OS);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.U1),this.T(a,"onAutonavCoundownStarted",this.q9))},o6=function(a){var b=a.J.yn(!0,a.J.isFullscreen());
g.jv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Fg(b));g.jv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.CK);g.jv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.wf());g.jv(a.J.getRootNode(),"countdown-running",a.Sk());g.jv(a.container.element,"ytp-player-content",a.J.wf());g.hs(a.overlay.element,{width:b.width+"px"});if(!a.Sk()){a.J.wf()?Orb(a,Math.round(Prb(a)/1E3)):Orb(a);b=!!a.suggestion&&!!a.suggestion.Wr;var c=a.J.wf()||!b;
g.jv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.jv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.qG(a.B,a.J.wf());g.jv(a.element,"ytp-enable-w2w-color-transitions",Qrb(a))}},Nrb=function(a){var b=Prb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Orb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Sk()?a.select(!0):a.Sk()&&a.D.start()},Prb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.FB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Gs()?a.J.Gs():g.DJ(a.J.U().experiments,"autoplay_time")||1E4},Mrb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.Z5;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Qrb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},Orb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ha("ytp-autonav-endscreen-upnext-header");g.uf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.sf("Up next in $SECONDS".slice(0,d)));var e=g.rf("span");g.Yu(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.zf(e,b);a.appendChild(e);a.appendChild(g.sf("Up next in $SECONDS".slice(d+c.length)));return}}g.zf(a,"Up next")},p6=function(a,b){g.V.call(this,{I:"div",
La:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.V.call(this,{I:"div",
La:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",ya:"Up Next"},{I:"span",S:"ytp-upnext-title",ya:"{{title}}"},{I:"span",S:"ytp-upnext-author",ya:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
ya:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ha("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Su(this.bH,5E3,this);this.B=0;var b=this.Ha("ytp-upnext-cancel");this.cancelButton=new g.V({I:"button",La:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel autoplay"},ya:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Ta("click",this.W1,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.N(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ha("ytp-upnext-autoplay-icon");this.T(b,"click",this.X1);this.api.createClientVe(b,this,115130);this.QS();this.T(a,"autonavvisibility",this.QS);this.T(a,"mdxnowautoplaying",this.b$);this.T(a,"mdxautoplaycanceled",this.c$);g.jv(this.element,"ytp-upnext-mobile",this.api.U().B)},Rrb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.FB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Gs()?a.api.Gs():g.DJ(a.api.U().experiments,"autoplay_time")||1E4},Srb=function(a,b){b=Rrb(a,b);
var c=Math,d=c.min;var e=(0,g.HD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Sk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Sk()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",La:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ya:"More videos"}]});this.N=new g.V({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new n6(this.player);g.N(this,this.B);this.B.Ja(this.element);a.getVideoData().Sf?this.j=this.B:(this.j=new q6(a),g.BU(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.V({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.XK(this);g.N(this,this.D);g.N(this,this.table);this.table.Ja(this.element);this.table.show();g.N(this,this.N);this.N.Ja(this.table.element);this.hide()},s6=function(a){var b=a.wf();
b!==a.G&&(a.G=b,a.player.qa("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},t6=function(a,b){g.V.call(this,{I:"button",
La:["ytp-watch-on-youtube-button","ytp-button"],ya:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.x_();2===this.buttonType&&g.fv(this.element,"ytp-continue-watching-button");this.Ta("click",this.onClick);this.Ta("videodatachange",this.x_);g.qG(this,!0)},u6=function(a,b){p6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.We=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new t6(a,2);g.N(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},Trb=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.V({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",ya:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.xW("Subscribe",null,"Unsubscribe",null,!0,!1,b.El,b.subscribed,"trailer-endscreen",null,a,!1);g.N(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ha("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},v6=function(a){var b=a.U(),c=g.VK||g.fS?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.V.call(this,{I:"a",La:e,Y:{href:"{{url}}",target:d?b.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",Y:c,V:[{I:"span",S:"ytp-videowall-still-info-title",ya:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",ya:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",ya:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",ya:"{{duration}}"}]}]}]},{I:"span",La:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",ya:"{{playlist_length}}"},")"]}]},{I:"span",La:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",ya:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.XK(this);g.N(this,this.j);this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},w6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.X=null;this.B=new g.XK(this);g.N(this,this.B);this.K=new g.Su(function(){g.fv(b.element,"ytp-show-tiles")},0);
g.N(this,this.K);var c=new g.V({I:"button",La:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},V:[g.wG()]});g.N(this,c);c.Ja(this.element);c.Ta("click",this.d2,this);this.table=new g.nG({I:"div",S:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ja(this.element);c=new g.V({I:"button",La:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},V:[g.xG()]});g.N(this,c);c.Ja(this.element);c.Ta("click",this.b2,this);a.getVideoData().Sf?this.j=new n6(a,!0):this.j=new q6(a);
g.N(this,this.j);g.BU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},x6=function(a){return g.CU(a.player)&&a.AC()&&!a.D},y6=function(a){var b=a.wf();
b!==a.N&&(a.N=b,a.player.qa("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.N(this,this.watchButton);this.watchButton.Ja(this.element);g.cgb(a)&&(this.j=new g.z2(a),g.N(this,this.j),this.B=new g.V({I:"div",La:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},V:[this.j]}),g.N(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},Xrb=function(a){g.QV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.XK(this);g.N(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.HC(g.oS(c))&&d&&!g.yU(a)?(this.B=!0,this.endScreen=new u6(a,g.pU(a))):a.hd()?this.endScreen=new z6(a):Urb(a)?(this.D=!0,Vrb(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(a)):c.Og?this.endScreen=new Trb(a):this.endScreen=new p6(a);g.N(this,this.endScreen);g.BU(a,this.endScreen.element,4);Wrb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.kK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.lK("endscreen"),function(e){b.onCueRangeExit(e)})},Vrb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Il&&a.C===b.Sf)return!1;a.j=b.Il;a.C=b.Sf;return!0},Urb=function(a){a=a.U();
return a.ke&&!a.Og},Wrb=function(a){a.player.Af("endscreen");
var b=a.player.getVideoData();b=new g.jK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.jK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.tf([b,c])};
g.uU.prototype.Gs=g.ea(16,function(){return this.app.Gs()});
g.e1.prototype.Gs=g.ea(15,function(){return this.getVideoData().BU});
g.qU.prototype.yr=g.ea(14,function(a){this.xi().yr(a)});
g.YW.prototype.yr=g.ea(13,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.eY.prototype.yr=g.ea(12,function(a){this.overflowButton&&this.overflowButton.yr(a)});
g.qU.prototype.zr=g.ea(11,function(a){this.xi().zr(a)});
g.cX.prototype.zr=g.ea(10,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.eY.prototype.zr=g.ea(9,function(a){this.shareButton&&this.shareButton.zr(a)});
g.qU.prototype.eB=g.ea(8,function(a){this.xi().eB(a)});
g.qW.prototype.eB=g.ea(7,function(a){this.zQ!==a&&(this.zQ=a,this.Zp())});
g.qU.prototype.dB=g.ea(6,function(a){this.xi().dB(a)});
g.eY.prototype.dB=g.ea(5,function(a){this.yQ!==a&&(this.yQ=a,this.Yp())});g.w(m6,g.V);m6.prototype.select=function(){this.J.Fo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.VC||void 0)&&this.J.logClick(this.element)};
m6.prototype.onClick=function(a){g.YU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(n6,g.V);g.k=n6.prototype;g.k.oG=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.updateValue("url",this.suggestion.Ok()),o6(this))};
g.k.Sk=function(){return 0<this.C};
g.k.mB=function(){this.Sk()||(this.C=Date.now(),Nrb(this),Lrb(this.J,Prb(this)),g.jv(this.J.getRootNode(),"countdown-running",this.Sk()))};
g.k.Nw=function(){this.Up();Nrb(this);var a=this.j.Ha("ytp-autonav-endscreen-upnext-header");a&&g.zf(a,"Up next")};
g.k.Up=function(){this.Sk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Up()};
g.k.PS=function(a){g.YU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ha("ytp-autonav-endscreen-link-container")&&(a=this.j.Ha("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.kb("innertubeCommand",this.K),this.Up()):this.select())};
g.k.V1=function(){this.J.logClick(this.cancelButton.element);g.wU(this.J,!0);this.G&&this.J.kb("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Mrb(this,b);var c;this.G=null==(c=b.R5)?void 0:c.command};
g.k.q9=function(a){if(Qrb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.rH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.rH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.rH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.rH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.rH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.rH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.jv(this.element,"ytp-w2w-animate",!0)}};
g.k.U1=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.jv(this.element,"ytp-w2w-animate",!1)};
g.k.OS=function(){var a=this.J.wf();this.N&&this.Gb!==a&&g.qG(this,a);o6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ha("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Fg=function(a){return 400>a.width||459>a.height};g.w(p6,g.V);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.AC=function(){return!1};
g.k.wf=function(){return!1};
g.k.KX=function(){return!1};g.w(q6,g.V);g.k=q6.prototype;g.k.bH=function(){this.notification&&(this.D.stop(),this.Sc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.oG=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.QS=function(){g.qG(this,this.api.wf());this.api.logVisibility(this.element,this.api.wf());this.api.logVisibility(this.Ha("ytp-upnext-autoplay-icon"),this.api.wf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.wf())};
g.k.k$=function(){window.focus();this.bH()};
g.k.mB=function(a){var b=this;this.Sk()||(g.QE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.HD)(),this.j=new g.Su(function(){Srb(b,a)},25),Srb(this,a),Lrb(this.api,Rrb(this,a)));
g.hv(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Sk=function(){return!!this.j};
g.k.Nw=function(){this.Up();this.B=(0,g.HD)();Srb(this);g.fv(this.element,"ytp-upnext-autoplay-paused")};
g.k.Up=function(){this.Sk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.bH(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.dh()}),this.C=this.T(this.notification,"click",this.k$),this.D.start())}this.Up();this.api.nextVideo(!1,a)};
g.k.X1=function(a){!g.yf(this.cancelButton.element,a.target)&&g.YU(a,this.api)&&(this.api.wf()&&this.api.logClick(this.Ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.W1=function(){this.api.wf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.wU(this.api,!0)};
g.k.b$=function(a){this.api.getPresentingPlayerType();this.show();this.mB(a)};
g.k.c$=function(){this.api.getPresentingPlayerType();this.Up();this.hide()};
g.k.xa=function(){this.Up();this.bH();g.V.prototype.xa.call(this)};g.w(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.D.T(this.player,"appresize",this.NB);this.D.T(this.player,"onVideoAreaChange",this.NB);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.RS);this.D.T(this.player,"onAutonavCancelled",this.Y1);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.wU(this.player,!1);g.CU(this.player)&&this.AC()&&!this.C?(s6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.mB():3===this.videoData.autonavState&&this.j.Nw()):(g.wU(this.player,!0),s6(this));this.NB()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.Nw();s6(this)};
g.k.NB=function(){var a=this.player.yn(!0,this.player.isFullscreen());s6(this);o6(this.B);g.jv(this.element,"ytp-autonav-cancelled-small-mode",this.Fg(a));g.jv(this.element,"ytp-autonav-cancelled-tiny-mode",this.DI(a));g.jv(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.hs(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.jv(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.uT(this.videoData);b&&(this.j.oG(b),this.j!==this.B&&this.B.oG(b))}if(a&&a.length)for(b=0;b<Yrb.length;++b){var c=Yrb[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.N(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.NB()}};
g.k.RS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Up(),this.Gb&&this.NB()):(this.K=!0,this.wf()&&(2===a?this.j.mB():3===a&&this.j.Nw()))};
g.k.Y1=function(a){a?this.RS(1):(this.C=null,this.K=!1)};
g.k.AC=function(){return 1!==this.videoData.autonavState};
g.k.Fg=function(a){return(910>a.width||459>a.height)&&!this.DI(a)&&!(400>=a.width||360>=a.height)};
g.k.DI=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.wf=function(){return this.Gb&&g.CU(this.player)&&this.AC()&&!this.C};
var Yrb=[1,3,2,4];g.w(t6,g.V);g.k=t6.prototype;g.k.x_=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.ZU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.gS(b)){var c={};g.gS(b)&&g.jU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.EP(c,b);a=g.Pm(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Gb&&this.Z)};
g.k.show=function(){g.V.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.V.prototype.hide.call(this);this.logVisibility()};
g.k.Lc=function(a){g.V.prototype.Lc.call(this,a);this.logVisibility()};g.w(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.We.dB(!0),this.We.zr(!0),this.J.U().je||this.We.yr(!0),this.J.logVisibility(this.element,!0),this.watchButton.Lc(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.We.dB(!1);this.We.zr(!1);this.We.yr(!1);this.J.logVisibility(this.element,!1);this.watchButton.Lc(!1)};g.w(Trb,p6);Trb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.El;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(v6,g.V);v6.prototype.select=function(){this.api.Fo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.VC||void 0)&&this.api.logClick(this.element)};
v6.prototype.onClick=function(a){if(g.gS(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Ok(),c={};g.WTa(this.api,c,"emb_rel_end");b=g.Pm(b,c);g.ZU(b,this.api,a)}else g.YU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Lf?!1:b.D};g.w(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.cq();this.B.T(this.player,"appresize",this.cq);this.B.T(this.player,"onVideoAreaChange",this.cq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.wL);this.B.T(this.player,"onAutonavCancelled",this.Z1);a=this.videoData.autonavState;a!==this.X&&this.wL(a);this.B.T(this.element,"transitionend",this.Caa)};
g.k.destroy=function(){g.WC(this.B);g.wb(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.hv(this.element,"ytp-show-tiles");this.K.stop();this.X=this.videoData.autonavState};
g.k.AC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Gb;p6.prototype.show.call(this);g.hv(this.element,"ytp-show-tiles");this.player.U().B?g.Uu(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.wU(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.mB():3===this.videoData.autonavState&&this.j.Nw()):(g.wU(this.player,!0),y6(this));a!==this.Gb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Gb;p6.prototype.hide.call(this);this.j.Nw();y6(this);a!==this.Gb&&this.player.logVisibility(this.element,!1)};
g.k.Caa=function(a){a.target===this.element&&this.cq()};
g.k.cq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.uT(d)];if(e.length){g.fv(this.element,"ytp-endscreen-paginate");var f=this.J.yn(!0,this.J.isFullscreen());if(a=g.pU(this.J))a=a.qh()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.rs(f,n,p);g.hs(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.oG(g.uT(this.videoData));this.j instanceof
n6&&o6(this.j);g.jv(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.ve(q+this.C,c),0!==t){r=this.stills[h];r||(r=new v6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var x=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-v-4,E=Math.floor(n*(l+t)/a)-x-4;g.ns(r.element,x,v);g.rs(r.element,E,B);g.hs(r.element,"transitionDelay",
(m+l)/20+"s");g.jv(r.element,"ytp-videowall-still-mini",1===t);g.jv(r.element,"ytp-videowall-still-large",2<t);t=Math.max(E,B);g.jv(r.element,"ytp-videowall-still-round-large",256<=t);g.jv(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.jv(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.Zu(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(r,q,v),g.gS(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Ok(),v={},g.jU(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.Pm(t,g.EP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.jv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.wf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.cq())};
g.k.b2=function(){this.C+=this.stills.length;this.cq()};
g.k.d2=function(){this.C-=this.stills.length;this.cq()};
g.k.KX=function(){return this.j.Sk()};
g.k.wL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Up(),this.Gb&&this.cq()):(this.G=!0,this.Gb&&x6(this)&&(2===a?this.j.mB():3===a&&this.j.Nw()))};
g.k.Z1=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.wL(1)}else this.D=null,this.G=!1;this.cq()};
g.k.wf=function(){return this.Gb&&x6(this)};g.w(z6,p6);z6.prototype.KD=function(){var a;return null==(a=this.j)?void 0:a.KD()};
z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.KD();g.jv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.pU(this.player))||c.eB(!0);this.player.logVisibility(this.element,!0);this.watchButton.Lc(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.pU(this.player))||a.eB(!1);this.player.logVisibility(this.element,!1);this.watchButton.Lc(!1)};g.w(Xrb,g.QV);g.k=Xrb.prototype;g.k.Wt=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.hd()||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.uT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Urb(this.player)||d;a=a.nk;c=this.player.jD();return d&&!a&&!c&&!b};
g.k.wf=function(){return this.endScreen.wf()};
g.k.Z7=function(){return this.wf()?this.endScreen.KX():!1};
g.k.xa=function(){this.player.Af("endscreen");g.QV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().Ke.get("heartbeat"),d=g.uT(a);!d||b.videoId!==d.videoId||a.BS?(this.player.Fo(b.videoId,void 0,void 0,!0,!0,b),c&&c.QI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.QV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.QV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Wt()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Wrb(this);this.D&&Vrb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.N(this,this.endScreen),g.BU(this.player,this.endScreen.element,4))};g.PV("endscreen",Xrb);})(_yt_player);
